"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const student_controller_1 = require("../controllers/student_controller");
const router = (0, express_1.Router)();
router.post('/checkstudent', student_controller_1.checkStudent);
router.post('/register', student_controller_1.insertStudent);
router.post('/login', student_controller_1.verifyLogin);
router.post('/savepassword', student_controller_1.savePassword);
router.post('/payment/:id', student_controller_1.saveOrder);
router.post('/checkcourse', student_controller_1.checkPurchased);
router.get('/gettutors', student_controller_1.getAllTutors);
router.get('/getallchats/:id', student_controller_1.getAllChats);
router.post('/connection', student_controller_1.chatConnection);
router.get('/getallmessages/:id', student_controller_1.getMessages);
router.post('/sendmessage', student_controller_1.createMessage);
exports.default = router;
